FROM anothersoftwaredevelopmentblog/docker-v8:latest

RUN CHECKOUT=master   ARCH=x64.release   /make-v8.sh /

#RUN mkdir -p /repo/v8/out/x64.release/lib.target
#ADD libv8-static-x64.release.tar /repo/v8/out/x64.release/lib.target



ENTRYPOINT sudo /startup.sh /



